import type { ProjectDefinition, TimelineItem, Transition } from "@/domain/project";

export type FfmpegPlan = { sourcePaths: Map<string, string>; assetPaths?: Map<string, string>; outputPath: string; args: string[] };
function formatSeconds(value: number): string { return value.toFixed(3).replace(/0+$/, "").replace(/\.$/, ""); }
function escapeFilterText(value: string): string { return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/:/g, "\\:").replace(/,/g, "\\,").replace(/\[/g, "\\[").replace(/\]/g, "\\]").replace(/\n/g, "\\n"); }
function transitionDuration(transition: Transition | undefined, duration: number): number { if (!transition || transition.type === "cut" || transition.durationSeconds <= 0) return 0; return Math.min(transition.durationSeconds, duration / 2); }
function sourceVideoFilter(inputIndex: number, start: number, duration: number, label: string): string { return `[${inputIndex}:v]trim=start=${formatSeconds(start)}:duration=${formatSeconds(duration)},scale=w=1920:h=1080,setsar=1,setpts=PTS-STARTPTS[${label}]`; }
function sourceAudioFilter(inputIndex: number, start: number, duration: number, label: string): string { return `[${inputIndex}:a]atrim=start=${formatSeconds(start)}:duration=${formatSeconds(duration)},asetpts=PTS-STARTPTS,aresample=48000,aformat=sample_fmts=fltp:sample_rates=48000:channel_layouts=stereo[${label}]`; }

type RichLayer = { id?: string; type?: string; x?: number; y?: number; width?: number; height?: number; rotation?: number; text?: string; src?: string; animation?: string; style?: Record<string, string | number> };
function richLayers(item: TimelineItem): RichLayer[] { try { const raw = item.data?.layers; const parsed = raw ? JSON.parse(raw) : []; return Array.isArray(parsed) ? parsed : []; } catch { return []; } }
function layerStyle(layer: RichLayer) { const style = layer.style ?? {}; return { fontSize: Number.parseFloat(String(style["font-size"] ?? 48)), color: String(style.color ?? "white"), fontWeight: String(style["font-weight"] ?? "normal"), fontFamily: String(style["font-family"] ?? ""), textAlign: String(style["text-align"] ?? "left"), opacity: Number(style.opacity ?? 1), boxColor: style.background ? String(style.background) : undefined, textShadow: style["text-shadow"] ? String(style["text-shadow"]) : undefined }; }
function richLayerFilters(input: string, output: string, item: TimelineItem, layers: RichLayer[], width: number, height: number, textColor: string, imageIndexByAsset: Map<string, number>, counter: { value: number }, fontFile?: string, enable?: { start: number; end: number }): string[] {
  const filters: string[] = []; let current = input;
  for (const layer of layers) {
    const next = `${output}_${counter.value++}`; const x = Number(layer.x ?? 0); const y = Number(layer.y ?? 0); const w = Number(layer.width ?? width); const h = Number(layer.height ?? height); const s = layerStyle(layer); const enableExpr = enable ? `:enable='between(t,${formatSeconds(enable.start)},${formatSeconds(enable.end)})'` : "";
    if (layer.type === "rect" || layer.type === "ellipse") {
      const color = layer.style?.background ? String(layer.style.background) : "black";
      const shape = layer.type === "ellipse" ? `drawbox=x=${formatSeconds(x)}:y=${formatSeconds(y)}:w=${formatSeconds(w)}:h=${formatSeconds(h)}:color=${color}@${s.opacity}:t=fill` : `drawbox=x=${formatSeconds(x)}:y=${formatSeconds(y)}:w=${formatSeconds(w)}:h=${formatSeconds(h)}:color=${color}@${s.opacity}:t=fill`;
      filters.push(`[${current}]${shape}${enableExpr}[${next}]`);
    } else if (layer.type === "image" && layer.src && imageIndexByAsset.has(layer.src)) {
      const idx = imageIndexByAsset.get(layer.src)!; filters.push(`[${idx}:v]format=rgba,colorchannelmixer=aa=${s.opacity}[${next}img]`); filters.push(`[${current}][${next}img]overlay=x=${formatSeconds(x)}:y=${formatSeconds(y)}:w=${formatSeconds(w)}:h=${formatSeconds(h)}${enableExpr}[${next}]`);
    } else if (layer.type === "text" && layer.text) {
      const font = fontFile ? `:fontfile='${escapeFilterText(fontFile)}'` : ""; const alignX = s.textAlign === "center" ? `(w-text_w)/2` : s.textAlign === "right" ? `w-text_w-${formatSeconds(width - x - w)}` : formatSeconds(x); const textY = formatSeconds(y); const box = s.boxColor ? `:box=1:boxcolor=${s.boxColor}@${s.opacity}:boxborderw=10` : "";
      filters.push(`[${current}]drawtext=text='${escapeFilterText(layer.text)}':fontcolor=${s.color || textColor}:fontsize=${s.fontSize}:x=${alignX}:y=${textY}:fontcolor_expr='${s.color || textColor}'${box}${font}${enableExpr}[${next}]`);
    } else continue;
    current = next;
  }
  if (current !== input) filters.push(`[${current}]null[${output}]`); else filters.push(`[${input}]null[${output}]`);
  return filters;
}

function slateFilters(inputIndex: number, item: Extract<TimelineItem, { type: "slate" }>, label: string, height: number, width: number, textColor: string, imageIndexByAsset: Map<string, number>, counter: { value: number }, fontFile?: string): string[] {
  const filters = [`[${inputIndex}:v]scale=w=${width}:h=${height},setsar=1,setpts=PTS-STARTPTS[${label}base]`];
  const layers = richLayers(item);
  if (layers.length) return [...filters, ...richLayerFilters(`${label}base`, label, item, layers, width, height, textColor, imageIndexByAsset, counter, fontFile)];
  const text = item.data.title ?? item.data.text; const subtitle = item.data.subtitle; const font = fontFile ? `:fontfile='${escapeFilterText(fontFile)}'` : "";
  if (text) filters.push(`[${label}base]drawtext=text='${escapeFilterText(text)}':fontcolor=${textColor}:fontsize=${Math.round(height * 0.065)}:x=(w-text_w)/2:y=(h-text_h)/2${font}[${label}title]`);
  if (subtitle) { const previous = text ? `${label}title` : `${label}base`; filters.push(`[${previous}]drawtext=text='${escapeFilterText(subtitle)}':fontcolor=${textColor}:fontsize=${Math.round(height * 0.035)}:x=(w-text_w)/2:y=h*0.65${font}[${label}]`); } else if (text) filters[filters.length - 1] = filters[filters.length - 1].replace(`[${label}title]`, `[${label}]`); else filters[0] = filters[0].replace(`[${label}base]`, `[${label}]`);
  return filters;
}
function overlayTextFilter(input: string, output: string, text: string, item: Extract<TimelineItem, { type: "overlay" }>, textColor: string, fontFile?: string): string { const font = fontFile ? `:fontfile='${escapeFilterText(fontFile)}'` : ""; const fontSize = Number(item.data.fontSize ?? 48); const color = item.data.color ?? `${textColor}@${item.opacity}`; const x = item.x === undefined ? "(w-text_w)/2" : formatSeconds(item.x); const y = item.y === undefined ? "(h-text_h)/2" : formatSeconds(item.y); const box = item.data.boxColor ? `:box=1:boxcolor=${item.data.boxColor}:boxborderw=${item.data.boxBorderWidth ?? 20}` : ""; return `[${input}]drawtext=text='${escapeFilterText(text)}':fontcolor=${color}:fontsize=${fontSize}:x=${x}:y=${y}${box}:enable='between(t,${formatSeconds(item.startSeconds)},${formatSeconds(item.endSeconds)})'${font}[${output}]`; }

export function buildCompositionRenderPlan(definition: ProjectDefinition, sourcePaths: Map<string, string>, outputPath: string, assetPaths?: Map<string, string>): FfmpegPlan {
  const template = (definition.template ?? {}) as Partial<Record<string, unknown>>; const width = (template.width as number | undefined) ?? 1920; const height = (template.height as number | undefined) ?? 1080; const fps = (template.fps as number | undefined) ?? 30; const backgroundColor = (template.backgroundColor as string | undefined) ?? "black"; const textColor = (template.textColor as string | undefined) ?? "white"; const items = definition.composition.items;
  const baseItems = items.filter(item => item.type === "source-clip" || (item.type === "slate" && item.mode !== "overlay")); const overlays = items.filter((item): item is Extract<TimelineItem, { type: "overlay" }> => item.type === "overlay"); const overlaySlates = items.filter((item): item is Extract<TimelineItem, { type: "slate" }> => item.type === "slate" && item.mode === "overlay"); if (!baseItems.length) throw new Error("Composition must contain at least one source clip or standalone slate");
  const sourceIds = Array.from(new Set(baseItems.filter((i): i is Extract<TimelineItem, { type: "source-clip" }> => i.type === "source-clip").map(i => i.sourceId))); const sourceIndexMap = new Map(sourceIds.map((id,index)=>[id,index])); for (const sourceId of sourceIds) if (!sourcePaths.has(sourceId)) throw new Error(`Missing source path for sourceId: ${sourceId}`);
  const args: string[] = ["-hide_banner","-y"]; for (const sourceId of sourceIds) args.push("-i",sourcePaths.get(sourceId)!);
  const filters: string[]=[]; const videoLabels:string[]=[]; const audioLabels:string[]=[]; const durations:number[]=[]; let nextInput=sourceIds.length;
  // Gather all image assets referenced by rich graphics before adding image inputs.
  const imageAssets = new Set<string>(); for (const item of [...overlays,...overlaySlates]) { if (item.type === "overlay" && item.kind === "image" && item.imageAsset) imageAssets.add(item.imageAsset); if (item.type === "slate" && item.backgroundImage) imageAssets.add(item.backgroundImage); for (const l of richLayers(item)) if (l.type === "image" && l.src) imageAssets.add(l.src); }
  const imageIndexByAsset = new Map<string,number>(); for (const key of imageAssets) { if (!assetPaths?.has(key)) continue; imageIndexByAsset.set(key,nextInput); args.push("-loop","1","-i",assetPaths.get(key)!); nextInput++; }
  const counter={value:0};
  baseItems.forEach((item,index)=>{ const duration=item.type === "slate" ? item.durationSeconds : item.endSeconds-item.startSeconds; durations.push(duration); const v=`v${index}`,a=`a${index}`; videoLabels.push(v); audioLabels.push(a); if(item.type === "source-clip"){const input=sourceIndexMap.get(item.sourceId)!; filters.push(sourceVideoFilter(input,item.startSeconds,duration,v)); filters.push(sourceAudioFilter(input,item.startSeconds,duration,a));} else { const video=nextInput++; const audio=nextInput++; if(item.backgroundImage && assetPaths?.has(item.backgroundImage)){args.push("-loop","1","-i",assetPaths.get(item.backgroundImage)!);} else args.push("-f","lavfi","-i",`color=c=${backgroundColor}:s=${width}x${height}:r=${fps}:d=${formatSeconds(duration)}`); args.push("-f","lavfi","-i","anullsrc=channel_layout=stereo:sample_rate=48000"); filters.push(...slateFilters(video,item,v,height,width,textColor,imageIndexByAsset,counter,template.fontFile as string|undefined)); filters.push(`[${audio}:a]atrim=duration=${formatSeconds(duration)},asetpts=PTS-STARTPTS,aresample=48000,aformat=sample_fmts=fltp:sample_rates=48000:channel_layouts=stereo[${a}]`); }});
  let currentVideo=videoLabels[0], currentAudio=audioLabels[0], currentDuration=durations[0];
  for(let index=1;index<baseItems.length;index++){const item=baseItems[index],duration=durations[index],transition=item.transitionIn,d=transitionDuration(transition,Math.min(currentDuration,duration)),nextVideo=`vc${index}`,nextAudio=`ac${index}`; if(transition?.type==="crossfade"&&d>0){filters.push(`[${currentVideo}][${videoLabels[index]}]xfade=transition=fade:duration=${formatSeconds(d)}:offset=${formatSeconds(currentDuration-d)}[${nextVideo}]`);filters.push(`[${currentAudio}][${audioLabels[index]}]acrossfade=d=${formatSeconds(d)}:curve1=tri:curve2=tri[${nextAudio}]`);currentDuration+=duration-d;}else if(transition?.type==="fade"&&d>0){const outV=`vfout${index}`,inV=`vfin${index}`,outA=`afout${index}`,inA=`afin${index}`;filters.push(`[${currentVideo}]fade=t=out:st=${formatSeconds(currentDuration-d)}:d=${formatSeconds(d)}[${outV}]`);filters.push(`[${videoLabels[index]}]fade=t=in:st=0:d=${formatSeconds(d)}[${inV}]`);filters.push(`[${currentAudio}]afade=t=out:st=${formatSeconds(currentDuration-d)}:d=${formatSeconds(d)}[${outA}]`);filters.push(`[${audioLabels[index]}]afade=t=in:st=0:d=${formatSeconds(d)}[${inA}]`);filters.push(`[${outV}][${inV}][${outA}][${inA}]concat=n=2:v=1:a=1[${nextVideo}][${nextAudio}]`);currentDuration+=duration;}else{filters.push(`[${currentVideo}][${videoLabels[index]}][${currentAudio}][${audioLabels[index]}]concat=n=2:v=1:a=1[${nextVideo}][${nextAudio}]`);currentDuration+=duration;}currentVideo=nextVideo;currentAudio=nextAudio;}
  let outputVideo=currentVideo; let overlayCounter=0;
  for(const item of overlays){const next=`ol${overlayCounter++}`; const layers=richLayers(item); if(layers.length){filters.push(...richLayerFilters(outputVideo,next,item,layers,width,height,textColor,imageIndexByAsset,counter,template.fontFile as string|undefined,{start:item.startSeconds,end:item.endSeconds})); outputVideo=next; continue;} if(item.kind==="rectangle"){const x=item.x??0,y=item.y??0,w=item.width??width,h=item.height??height,color=item.color??item.data.color??"black";filters.push(`[${outputVideo}]drawbox=x=${formatSeconds(x)}:y=${formatSeconds(y)}:w=${formatSeconds(w)}:h=${formatSeconds(h)}:color=${color}@${item.opacity}:t=fill:enable='between(t,${formatSeconds(item.startSeconds)},${formatSeconds(item.endSeconds)})'[${next}]`);}else if(item.kind==="image"&&item.imageAsset&&imageIndexByAsset.has(item.imageAsset)){const input=imageIndexByAsset.get(item.imageAsset)!;const x=item.x??0,y=item.y??0;filters.push(`[${input}:v]format=rgba,colorchannelmixer=aa=${item.opacity}[img${overlayCounter}]`);filters.push(`[${outputVideo}][img${overlayCounter}]overlay=x=${formatSeconds(x)}:y=${formatSeconds(y)}:enable='between(t,${formatSeconds(item.startSeconds)},${formatSeconds(item.endSeconds)})'[${next}]`);}else{const text=item.data.text??item.data.title;if(!text)continue;filters.push(overlayTextFilter(outputVideo,next,text,item,textColor,template.fontFile as string|undefined));}outputVideo=next;}
  for(const item of overlaySlates){const start=item.startSeconds!,end=item.endSeconds!,next=`sl${overlayCounter++}`;let current=outputVideo;const layers=richLayers(item);if(layers.length){filters.push(`[${current}]drawbox=x=0:y=0:w=${width}:h=${height}:color=${item.data.backgroundColor??backgroundColor}@${Number(item.data.backgroundOpacity??0.55)}:t=fill:enable='between(t,${formatSeconds(start)},${formatSeconds(end)})'[${next}bg]`);current=`${next}bg`;filters.push(...richLayerFilters(current,next,item,layers,width,height,textColor,imageIndexByAsset,counter,template.fontFile as string|undefined,{start,end}));outputVideo=next;continue;}filters.push(`[${current}]drawbox=x=0:y=0:w=${width}:h=${height}:color=${item.data.backgroundColor??backgroundColor}@${Number(item.data.backgroundOpacity??0.55)}:t=fill:enable='between(t,${formatSeconds(start)},${formatSeconds(end)})'[${next}bg]`);current=`${next}bg`;const text=item.data.title??item.data.text;if(text){filters.push(`[${current}]drawtext=text='${escapeFilterText(text)}':fontcolor=${textColor}:fontsize=${Math.round(height*0.065)}:x=(w-text_w)/2:y=(h-text_h)/2:enable='between(t,${formatSeconds(start)},${formatSeconds(end)})'[${next}text]`);current=`${next}text`;}filters.push(`[${current}]null[${next}]`);outputVideo=next;}
  args.push("-filter_complex",filters.join(";"),"-map",`[${outputVideo}]`,"-map",`[${currentAudio}]`,"-c:v","libx264","-preset","veryfast","-crf","20","-c:a","aac","-movflags","+faststart",outputPath); return {sourcePaths,assetPaths,outputPath,args};
}

export function buildSourceRenderPlan(definition: ProjectDefinition,inputPathOrSourcePaths:string|Map<string,string>,outputPath:string):FfmpegPlan { if(inputPathOrSourcePaths instanceof Map){if(definition.composition.items.length>0)return buildCompositionRenderPlan(definition,inputPathOrSourcePaths,outputPath);const legacyPath=inputPathOrSourcePaths.get("legacy-source")??inputPathOrSourcePaths.values().next().value;if(!legacyPath)throw new Error("No source path available for legacy render");return buildSourceRenderPlan(definition,legacyPath,outputPath);}const sourcePaths=new Map([["legacy-source",inputPathOrSourcePaths]]);if(definition.composition.items.length>0)return buildCompositionRenderPlan(definition,sourcePaths,outputPath);const start=definition.composition.sourceStartSeconds??0,end=definition.composition.sourceEndSeconds??0;return{sourcePaths,outputPath,args:["-hide_banner","-y","-i",inputPathOrSourcePaths,"-ss",formatSeconds(start),"-t",formatSeconds(end-start),"-map","0:v:0?","-map","0:a:0?","-c:v","libx264","-preset","veryfast","-crf","20","-c:a","aac","-movflags","+faststart",outputPath]}; }
